sudo: false

language: php

addons:
  apt:
    packages:
      - libcairo2-dev
      - libfreetype6-dev
      - fontconfig

php:
  - 7.0
  - 7.1
  - nightly
 
env: 
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff -q" 

before_script:
  - git clone https://github.com/eosforphp/datastructures.git
  - cd datastructures
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=eos_datastructures.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
install:
  - phpize
  - ./configure
  - make

script: 
  make test

notifications:
  email:
    auroraeosrose@gmail.com
