sudo: false

language: php

dist: bionic

addons:
  apt:
    packages:
      - libcairo2-dev
      - libfreetype6-dev
      - fontconfig
      - libjpeg-dev

php:
  - 8.0
  - nightly
 
env: 
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff -q -d extension=eos_datastructures.so" 

before_install:
  - git clone https://github.com/swen100/structures.git
  - pushd structures
  - phpize
  - ./configure --with-php-config=$(which php-config)
  - make
  - make install
  - echo "extension=eos_datastructures.so" > "$(phpenv prefix)/etc/conf.d/eos_datastructures.ini"
  - echo "extension=eos_datastructures.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - popd
  
install:
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=cairo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp ../structures/modules/eos_datastructures.so modules/eos_datastructures.so

script:
  make test

after_failure:
  - echo "$($(phpenv which php) -v)"
  - echo "$($(phpenv which php) -m)"

notifications:
  email:
    swen.zanon@geoglis.de
